/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister
import brilliant.arm.OpCode.factory.OpUtil.thumbExpandImm
import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

class ADD_A8_306 : ParseSupport() {

    override fun parse(data: Int): String {
        val type = getShiftInt(data, 25, 1)
        if (type == 0)
            return super.parse(data)
        return EncodingT4(data)
    }

    private fun EncodingT4(data: Int): String {

        val sb = StringBuilder("ADDW")
        sb.append(" ")
        val Rd = getShiftInt(data, 8, 4)
        val Rn = getShiftInt(data, 16, 4)
        val imm12 = getShiftInt(data, 26, 1) shl 11 or (getShiftInt(data, 12, 3) shl 8) or getShiftInt(data, 0, 8)

        sb.append(parseRegister(Rd))
        sb.append(" , ")
        sb.append(parseRegister(Rn))

        sb.append(" , #")
        sb.append(imm12)

        return sb.toString()
    }

    override fun getOpCode(data: Int): String? {
        return "ADD"
    }

    override fun getRd(data: Int): Int {
        return getShiftInt(data, 8, 4)
    }

    override fun getRn(data: Int): Int {
        return getShiftInt(data, 16, 4)
    }

    override fun getS(data: Int): Int {
        return getShiftInt(data, 20, 1)
    }

    override fun getShift(data: Int): Int {
        return thumbExpandImm(getShiftInt(data, 26, 1) shl 11 or (getShiftInt(data, 12, 3) shl 8) or getShiftInt(data, 0, 8))
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = ADD_A8_306()
    }

}