/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class BFC_A8_336 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "BFC.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = BFC_A8_336()
    }

}