/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class BFI_A8_338 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "BFI.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = BFI_A8_338()
    }

}