/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

class BXJ_A8_354 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "BXJ"
    }

    override fun getRm(data: Int): Int {
        return getShiftInt(data, 16, 4)
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = BXJ_A8_354()
    }

}