/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class ERET_B9_1982 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "ERET.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = ERET_B9_1982()
    }

}