/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister
import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

class LDRSB_A8_454 : ParseSupport() {

    override fun parse(data: Int): String {

        val sb = StringBuilder("LDRSB.W ")
        val Rt = getShiftInt(data, 12, 4)
        val Rn = getShiftInt(data, 16, 4)
        val Rm = getShiftInt(data, 0, 4)
        val imm2 = getShiftInt(data, 4, 2)

        sb.append(parseRegister(Rt))
        sb.append(" , [")
        sb.append(parseRegister(Rn))
        sb.append(" , ")
        sb.append(parseRegister(Rm))
        sb.append(" , LSL #")
        sb.append(imm2)
        sb.append("]")

        return sb.toString()
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = LDRSB_A8_454()
    }

}