/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class MOVT_A8_491 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "MOVT.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = MOVT_A8_491()
    }

}