/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class MSR_B9_1994 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "MSR.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = MSR_B9_1994()
    }

}