/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

class NOP : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "NOP"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = NOP()
    }

}