/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class PKH_A8_522 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "PKH"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = PKH_A8_522()
    }

}