/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class RFE_B9_2000 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "RFE.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = RFE_B9_2000()
    }

}