/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.thumbExpandImm
import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

class RSB_A8_574 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "RSB"
    }

    override fun getRd(data: Int): Int {
        return getShiftInt(data, 8, 4)
    }

    override fun getRn(data: Int): Int {
        return getShiftInt(data, 16, 4)
    }

    override fun getS(data: Int): Int {
        return getShiftInt(data, 20, 1)
    }

    override fun getShift(data: Int): Int {
        return thumbExpandImm(getShiftInt(data, 26, 1) shl 11 or (getShiftInt(data, 12, 3) shl 8) or getShiftInt(data, 0, 8))
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = RSB_A8_574()
    }

}