/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SBFX_A8_598 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SBFX.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SBFX_A8_598()
    }

}