/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

class SMLAL_A8_626 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        val n = getShiftInt(data, 5, 1)
        val m = getShiftInt(data, 4, 1)

        var opCode = "SMLAL"

        if (n == 0)
            opCode += "B"
        else
            opCode += "T"

        if (m == 0)
            opCode += "B"
        else
            opCode += "T"

        return opCode
    }

    override fun getRd(data: Int): Int {
        return getShiftInt(data, 12, 4)
    }

    override fun getRn(data: Int): Int {
        return getShiftInt(data, 8, 4)
    }

    override fun getRm(data: Int): Int {
        return getShiftInt(data, 16, 4)
    }

    override fun getShift(data: Int): Int {
        return getShiftInt(data, 0, 4)
    }

    override fun shifterRegister(): Boolean {
        return true
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMLAL_A8_626()
    }

}