/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SMLAWB_A8_630 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SMLAWB"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMLAWB_A8_630()
    }

}