/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SMLAD_A8_622 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SMLAD"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMLAD_A8_622()
    }

}