/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SMLSD_A8_632 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SMLSD"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMLSD_A8_632()
    }

}