/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SMMLA_A8_636 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SMMLA"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMMLA_A8_636()
    }

}