/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SMMLS_A8_638 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SMMLS"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMMLS_A8_638()
    }

}