/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SMMUL_A8_640 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SMMUL"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMMUL_A8_640()
    }

}