/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SMUAD_A8_642 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SMUAD"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMUAD_A8_642()
    }

}