/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SMULWB_A8_648 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SMULWB"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMULWB_A8_648()
    }

}