/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SRS_B9_2004 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SRS.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SRS_B9_2004()
    }

}