/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SSAT16_A8_654 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SSAT16"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SSAT16_A8_654()
    }

}