/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SSAT_A8_652 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SSAT.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SSAT_A8_652()
    }

}