/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class SUBS_B9_2010 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SUBS.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SUBS_B9_2010()
    }

}