/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class UBFX_A8_756 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "UBFX.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = UBFX_A8_756()
    }

}