/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class UDF_A8_758 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "UDF.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = UDF_A8_758()
    }

}