/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class USAD8_A8_792 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "USAD8"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = USAD8_A8_792()
    }

}