/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class USAT16_A8_798 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "USAT16.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = USAT16_A8_798()
    }

}