/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport

@Deprecated("")
class USAT_A8_796 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "USAT.W"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = USAT_A8_796()
    }

}