/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.signExtend
import brilliant.arm.OpCode.arm.instruction.support.ParseSupport
import brilliant.arm.OpCode.factory.Remotable

class B_A8_334 : ParseSupport(), Remotable {

    override fun getOpCode(data: Int): String {
        return "B"
    }

    override fun getShift(data: Int): Int {
        return signExtend(getShiftInt(data, 0, 24) shl 2, 24)
    }

    override fun performExecuteCommand(data: Int) {}

    override fun offset(data: Int): Int {
        return signExtend(getShiftInt(data, 0, 24) shl 2, 24)
    }

    companion object {

        val INSTANCE = B_A8_334()
    }

}