/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport
import brilliant.arm.OpCode.factory.CondFactory

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt

class BKPT_A8_346 : ParseSupport() {

    override fun getOpCode(data: Int): String {
        return "BKPT"
    }

    override fun getCond(data: Int): Int {
        val cond = super.getCond(data)

        if (cond != CondFactory.AL)
            error(data)
        return cond
    }

    override fun getShift(data: Int): Int {
        val imm12 = getShiftInt(data, 8, 12)
        val imm4 = getShiftInt(data, 0, 4)

        val imm = imm12 shl 12 or imm4

        return imm
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = BKPT_A8_346()
    }

}