/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class CDP_A8_358 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("CDP no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = CDP_A8_358()
    }

}