/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class LDC_A8_392 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("LDC no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = LDC_A8_392()
    }

}