/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class MCR_A8_476 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("MCR no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = MCR_A8_476()
    }

}