/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class MCRR_A8_478 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("MCRR no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = MCRR_A8_478()
    }

}