/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.factory.OpUtil.armExpandImm
import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

class MOV_A8_484 : ParseSupport() {

    override fun getOpCode(data: Int): String {
        return "MOV"
    }

    override fun getRd(data: Int): Int {
        return getShiftInt(data, 12, 4)
    }

    override fun getRn(data: Int): Int {
        return -1
    }

    override fun getRm(data: Int): Int {
        return -1
    }

    override fun getS(data: Int): Int {
        return getShiftInt(data, 20, 1)
    }

    override fun getType(data: Int): Int {
        return -1
    }

    override fun getShift(data: Int): Int {
        val mov = getShiftInt(data, 21, 7)
        if (mov == 29)
        // move imm12
            return armExpandImm(getShiftInt(data, 0, 12))
        else
            return getShiftInt(data, 16, 4) shl 12 or(getShiftInt(data, 0, 12)) // move imm16
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = MOV_A8_484()
    }

}