/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class MRC_A8_492 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("MRC no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = MRC_A8_492()
    }

}