/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class MRRC_A8_494 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("MRRC no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = MRRC_A8_494()
    }

}