/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class MSR_B9_1998 : ParseSupport() {

    override fun parse(data: Int): String? {
        error(data)
        return null
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = MSR_B9_1998()
    }

}