/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

class MSR_A8_498 : ParseSupport() {

    override fun getRd(data: Int): Int {
        return -1
    }

    override fun getRn(data: Int): Int {
        return -1
    }

    override fun getRm(data: Int): Int {
        return -1
    }

    override fun getS(data: Int): Int {
        return -1
    }

    override fun getType(data: Int): Int {
        return -1
    }

    override fun getShift(data: Int): Int {
        return 0
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = MSR_A8_498()
    }

}