/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

/**
 * @author Yoogurt
 * * SEV has no destination register
 */
class SEV_A8_606 : ParseSupport() {

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SEV_A8_606()
    }

}