/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport
import brilliant.arm.OpCode.factory.CondFactory

class SMLAWB_A8_630 : ParseSupport() {

    override fun parse(data: Int): String {

        val sb = StringBuilder("SMLAW")

        val Rd = getShiftInt(data, 16, 4)
        val Rn = getShiftInt(data, 0, 4)
        val Rm = getShiftInt(data, 8, 4)
        val Ra = getShiftInt(data, 12, 4)
        val M = getShiftInt(data, 6, 1)

        sb.append(getY(M))
        sb.append(CondFactory.parse(getCond(data)))
        sb.append(" ")

        sb.append(parseRegister(Rd))
        sb.append(" , ")
        sb.append(parseRegister(Rn))
        sb.append(" , ")
        sb.append(parseRegister(Rm))
        sb.append(" , ")
        sb.append(parseRegister(Ra))

        return sb.toString()

    }

    private fun getY(M: Int): String {

        if (M == 1)
            return "T"
        else
            return "B"
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMLAWB_A8_630()
    }

}