/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport
import brilliant.arm.OpCode.factory.OpUtil.getShiftInt

class SMLAL_A8_624 : ParseSupport() {

    override fun getS(data: Int): Int {
        return getShiftInt(data, 20, 1)
    }

    override fun getRd(data: Int): Int {
        return getShiftInt(data, 12, 4)
    }

    override fun getRn(data: Int): Int {
        return getShiftInt(data, 16, 4)
    }

    override fun getRm(data: Int): Int {
        return getShiftInt(data, 0, 4)
    }

    override fun getShift(data: Int): Int {
        return getShiftInt(data, 8, 4)
    }

    override fun shifterRegister(): Boolean {
        return true
    }

    override fun shifterUsed(): Boolean {
        return true
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMLAL_A8_624()
    }

}