/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class SMULBB_A8_644 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("SMLULBB no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMULBB_A8_644()
    }

}