/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class SMULWB_A8_648 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("SMULWB no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMULWB_A8_648()
    }

}