/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class SMULL_A8_646 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("SMULL no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SMULL_A8_646()
    }

}