/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class SRS_B9_2006 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("SRS no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SRS_B9_2006()
    }

}