/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class STC_A8_662 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("STC no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = STC_A8_662()
    }

}