/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class STM_B9_2008 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("STM no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = STM_B9_2008()
    }

}