/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class STRD_A8_688 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("STRD no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = STRD_A8_688()
    }

}