/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class STREX_A8_690 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("STREX no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = STREX_A8_690()
    }

}