/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class STRHT_A8_704 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("STRHT no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = STRHT_A8_704()
    }

}