/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class UMAAL_A8_774 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("UMAAL no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = UMAAL_A8_774()
    }

}