/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class UMLAL_A8_776 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("UMLAL no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = UMLAL_A8_776()
    }

}