/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport

@Deprecated("")
class UMULL_A8_778 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("UMULL no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = UMULL_A8_778()
    }

}