/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

class ASR_A8_330 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "ASRS"
    }

    override fun getRn(data: Int): String? {
        return parseRegister(getShiftInt(data, 0, 3))
    }

    override fun getRm(data: Int): String? {
        var imm5 = getShiftInt(data, 6, 5)
        if (imm5 == 0)
            imm5 = 0x20
        return parseRegister(getShiftInt(data, 3, 3)) + " , #" + imm5
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = ASR_A8_330()
    }
}