/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class BKPT_A8_346 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("BKPT no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = BKPT_A8_346()
    }

}