/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

class BLX_A8_350 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "BLX"
    }

    override fun getRn(data: Int): String? {
        return parseRegister(getShiftInt(data, 3, 4))
    }

    override fun getRm(data: Int): String? {
        return null
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = BLX_A8_350()
    }

}