/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport
import brilliant.elf.vm.Register

class CBZ_A8_356 : ParseSupport() {

    override fun getOpCode(data: Int): String? {

        val n = getShiftInt(data, 11, 1)

        if (n == 1)
            return "CBNZ"
        return "CBZ"
    }

    override fun getRn(data: Int): String? {
        return parseRegister(getShiftInt(data, 0, 3))
    }

    override fun getRm(data: Int): String? {
        return "#" + (getShiftInt(data, 3, 5) shl 1)
    }

    override fun getComment(data: Int): String? {
        if (Register.PC < 0)
            return null
        return "@" + Integer.toHexString(Register.PC + (getShiftInt(data, 3, 5) shl 1))
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = CBZ_A8_356()
    }

}