/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class CPS_B9_1978 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("CPS no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = CPS_B9_1978()
    }

}