/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

class LDR_A8_412 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "LDR"
    }

    override fun getRn(data: Int): String? {
        return parseRegister(getShiftInt(data, 0, 3))
    }

    override fun getRm(data: Int): String? {
        return parseRegister(getShiftInt(data, 3, 3)) + " , " +parseRegister(getShiftInt(data, 6, 3))
    }

    protected override val isRmMenory: Boolean
        get() = true

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = LDR_A8_412()
    }

}
