/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister
import brilliant.arm.OpCode.factory.OpUtil.align
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport
import brilliant.elf.vm.Register

/**
 * load from memory , <label> = [PC + zeroExtend(imm8:00)]
</label> */
class LDR_A8_410 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "LDR"
    }

    override fun getRn(data: Int): String? {
        return parseRegister(getShiftInt(data, 8, 3))
    }

    override fun getRm(data: Int): String? {
        return "#" + (getShiftInt(data, 0, 8) shl 2)
    }

    override fun getComment(data: Int): String? {
        if (Register.PC < 0)
            return null
        return "@" + Integer.toHexString(align(Register.PC, 4) + (getShiftInt(data, 0, 8) shl 2))
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = LDR_A8_410()
    }

}
