/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class LDRB_A8_416 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("LDRB no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = LDRB_A8_416()
    }

}