/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class LDRSB_A8_454 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("LDRSB no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = LDRSB_A8_454()
    }

}