/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

class LSL_A8_468 : ParseSupport() {

    override fun parse(data: Int): String {

        if (getShiftInt(data, 6, 5) == 0)
            return MOV_A8_486.INSTANCE.parse(data)

        return super.parse(data)
    }

    override fun getOpCode(data: Int): String? {
        return "LSLS"
    }

    override fun getRn(data: Int): String? {
        return parseRegister(getShiftInt(data, 0, 3))
    }

    override fun getRm(data: Int): String? {
        return parseRegister(getShiftInt(data, 3, 3)) + " , #"
        +getShiftInt(data, 6, 5)
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = LSL_A8_468()
    }

}