/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

class NOP_A8_510 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "NOP"
    }

    override fun getRn(data: Int): String? {
        return ""
    }

    override fun getRm(data: Int): String? {
        return null
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = NOP_A8_510()
    }
}