/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegisterList
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

class POP_A8_534 : ParseSupport() {

    override fun parse(data: Int): String {
        val M = getShiftInt(data, 8, 1)
        val registerList = getShiftInt(data, 0, 7)

        val sb = StringBuilder("POP ")
        sb.append("{")

        sb.append(parseRegisterList(registerList, -1))
        if (M == 1)
            sb.append(" , PC")
        sb.append("}")

        return sb.toString()
    }

    override fun getOpCode(data: Int): String? {
        return null
    }

    override fun getRn(data: Int): String? {
        return null
    }

    override fun getRm(data: Int): String? {
        return null
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = POP_A8_534()
    }

}
