/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class REV16_A8_564 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("REV16 no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = REV16_A8_564()
    }

}