/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

class SUB_A8_716 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SUB"
    }

    override fun getRn(data: Int): String? {
        return "SP"
    }

    override fun getRm(data: Int): String? {
        return "SP , #" + (getShiftInt(data, 0, 7) shl 2)
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SUB_A8_716()
    }
}
