/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
/*-------------------------------
 Auto Generated By AutoGenetate.java
 Don't remove or modify
 License GPL/GNU
 -------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.factory.OpUtil.getShiftInt
import brilliant.arm.OpCode.factory.OpUtil.parseRegister
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

class SUB_A8_712 : ParseSupport() {

    override fun getOpCode(data: Int): String? {
        return "SUBS"
    }

    override fun getRn(data: Int): String? {
        return parseRegister(getShiftInt(data, 0, 3))
    }

    override fun getRm(data: Int): String? {
        return parseRegister(getShiftInt(data, 3, 3)) + " , "+parseRegister(getShiftInt(data, 6, 3))
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SUB_A8_712()
    }

}