/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class SXTH_A8_734 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("SXTH no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = SXTH_A8_734()
    }

}