/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class UDF_A8_758 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("UDF no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = UDF_A8_758()
    }
}