/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class UXTH_A8_816 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("UXTH no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = UXTH_A8_816()
    }

}