/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class WFE_A8_1104 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("WFE no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = WFE_A8_1104()
    }

}