/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class WFI_A8_1106 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("WFI no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = WFI_A8_1106()
    }

}