/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport

@Deprecated("")
class YIELD_A8_1108 : ParseSupport() {

    override fun parse(data: Int): String {
        throw UnsupportedOperationException("YIELD no implements")
    }

    override fun performExecuteCommand(data: Int) {}

    companion object {

        val INSTANCE = YIELD_A8_1108()
    }

}